
import { StandardButton, Button, VerticalBox } from "std-widgets.slint";

import { Theme } from "./theme.slint";

// Import the global app logic, and then export it so build.rs picks it up, too.
import { AppLogic } from "./globals.slint";
export { AppLogic }

// Components making up the main UI 
import { EmulatorRegisters, Registers } from "./emu/registers.slint";
export { EmulatorRegisters }

import { AppControls } from "./emu/controls.slint";


export component MainWindow inherits Window {
    title: "eightyeighty — Intel 8080 Emulator";
    preferred-width: 1200px;
    preferred-height: 800px;
    background: Theme.app-background;

    MenuBar {
        Menu {
            title: @tr("File");
            MenuItem {
                title: @tr("Settings");
                activated => { AppLogic.cb-show-settings(); }
            }
            MenuItem {
                title: @tr("Exit");
                activated => { AppLogic.cb-exit(); }
            }
        }
        Menu {
            title: @tr("CPU");
            MenuItem {
                title: @tr("Reset");
            }
        }
    }


    GridLayout {
        
        Rectangle {
            col: 0;
            row: 0;
            rowspan: 3;
            width: 50%;
            height: 50%;
            Text {
                text: "Memory";
            }
        }
        Rectangle {
            col: 0;
            row: 3;
            rowspan: 2;
            width: 50%;
            height: 50%;
            Text {
                text: "Display";
            }            
        }
        Rectangle {
            col: 1;
            row: 0;
            min-height: 20px;
            max-height: 50px;
            vertical-stretch: 1;
            
            AppControls {}
        }
        Rectangle {
            col: 1;
            row: 1;
            min-height: 20px;
            vertical-stretch: 1;
            Text {
                text: "EMU State";
            }
    
        }
        Rectangle {
            col: 1;
            row: 2;
            min-height: 70px;
            vertical-stretch: 1;
            Text {
                text: "HW State";
            }            
        }
        Rectangle {
            col: 1;
            row: 3;
            height: 25%;
            
            Registers {}             
        }
        Rectangle {
            col: 1;
            row: 4;
            height: 25%;
            Text {
                text: "ROM Information";
            }                         
        }
    }
}

