
import { StandardButton, Button, VerticalBox } from "std-widgets.slint";
import { PlayIcon } from "@lucide"; 

export component SettingsDialog inherits Dialog {
    title: "Settings";

    VerticalBox{
        PlayIcon {
            size: 24px;
            colorize: #FFFFFF;
        }
    }

    StandardButton { kind: ok; }
    StandardButton { kind: cancel; }
}

export component MainWindow inherits Window {
    title: "eightyeighty — Intel 8080 Emulator";
    preferred-width: 1200px;
    preferred-height: 800px;

    callback cb-show-settings();
    callback cb-exit();

    MenuBar {
        Menu {
            title: @tr("File");
            MenuItem {
                title: @tr("Settings");
                activated => { root.cb-show-settings(); }
            }
            MenuItem {
                title: @tr("Exit");
                activated => { root.cb-exit(); }
            }
        }
        Menu {
            title: @tr("CPU");
            MenuItem {
                title: @tr("Reset");
            }
        }
    }
    GridLayout {
        
        Rectangle {
            background: #588fe0;
            col: 0;
            row: 0;
            rowspan: 3;
            width: 50%;
            height: 50%;
            Text {
                text: "Memory";
            }
            PlayIcon{
                size: 48px;
                colorize: #FFFFFF;
            }
        }
        Rectangle {
            background: #3e7d69;
            col: 0;
            row: 3;
            rowspan: 2;
            width: 50%;
            height: 50%;
            Text {
                text: "Display";
            }            
        }
        Rectangle {
            background: #c9e058; 
            col: 1;
            row: 0;
            min-height: 70px;
            max-height: 70px;
            Text {
                text: "Step / Run Controls";
            }
        }
        Rectangle {
            background: #6de058;
            col: 1;
            row: 1;
            min-height: 70px;
            Text {
                text: "EMU State";
            }
    
        }
        Rectangle {
            background: #58c5e0;
            col: 1;
            row: 2;
            min-height: 70px;
            Text {
                text: "HW State";
            }            
        }
        Rectangle {
            background: #e09e58;
            col: 1;
            row: 3;
            height: 25%;
            Text {
                text: "Regs";
            }             
        }
        Rectangle {
            background: #715f6c;
            col: 1;
            row: 4;
            height: 25%;
            Text {
                text: "ROM Information";
            }                         
        }
    }
}

