export global Theme {
    property<color> base-100: #faf7f5;
    property<color> base-200: #efeae6;
    property<color> base-300: #e7e2df;
    property<color> base-content: #291334;

    property<color> neutral: #262629;




    out property<color> app-background: Theme.base-200;

    out property<color> button: Theme.base-100;
    out property<color> button-hover: Theme.base-300;
    out property<color> border-color: Theme.base-300;
    out property<color> text: Theme.base-content;

    out property<color> icon-color: Theme.base-content;
    out property<length> icon-size: 24px;

    out property<length> padding: 8px;
    out property<length> radius: 6px;
    out property<length> gap: 6px;
    out property<length> border-width: 2px;
    
}