
import { StandardButton, Button, VerticalBox } from "std-widgets.slint";
import { PlayIcon, OctagonXIcon, StepForwardIcon, MicrochipIcon, 
         BadgeQuestionMarkIcon, RotateCcwIcon, FolderOpenIcon } from "@lucide"; 
import { Theme } from "../theme.slint";
import { AppLogic } from "../globals.slint";

component ControlButton inherits Rectangle {
    // in property<string> text;
    in property<image> icon;
    
    border-radius: Theme.radius;
    width: 64px;
    height: 32px;

    border-width: Theme.border-width;
    border-color: Theme.border-color;
}


export component AppControls inherits Rectangle {
    HorizontalLayout {
        spacing: Theme.gap;
        padding: Theme.padding;

        ControlButton {
            areaPlay := TouchArea { clicked => { AppLogic.cb-run(); } }
            background: areaPlay.has-hover ? Theme.button-hover : Theme.button;

            PlayIcon {
                size: Theme.icon-size;
                colorize: Theme.icon-color;
            }
        }
        ControlButton { 
            areaStop := TouchArea { clicked => { AppLogic.cb-stop(); } }
            background: areaStop.has-hover ? Theme.button-hover : Theme.button;

            OctagonXIcon {
                size: Theme.icon-size;
                colorize: Theme.icon-color;
            }
        }
        ControlButton {             
            areaStep := TouchArea { clicked => { AppLogic.cb-step(); } }
            background: areaStep.has-hover ? Theme.button-hover : Theme.button;

            StepForwardIcon {
                size: Theme.icon-size;
                colorize: Theme.icon-color;
            }
        }
        ControlButton { 
            areaHelp := TouchArea { clicked => { AppLogic.cb-reset(); } }
            background: areaHelp.has-hover ? Theme.button-hover : Theme.button;

            RotateCcwIcon {
                size: Theme.icon-size;
                colorize: Theme.icon-color;
            }
        }
        ControlButton { 
            areaOpen := TouchArea { clicked => { AppLogic.cb-insert-rom(); } }
            background: areaOpen.has-hover ? Theme.button-hover : Theme.button;

            FolderOpenIcon {
                size: Theme.icon-size;
                colorize: Theme.icon-color;
            }
        }        
        ControlButton { 
            areaRam := TouchArea { clicked => { AppLogic.cb-show-memory(); } }
            background: areaRam.has-hover ? Theme.button-hover : Theme.button;

            MicrochipIcon {
                size: Theme.icon-size;
                colorize: Theme.icon-color;
            }
        }          
    }
}