
import { StandardButton, Button, VerticalBox } from "std-widgets.slint";
import { PlayIcon, OctagonXIcon, StepForwardIcon, BadgeQuestionMarkIcon } from "@lucide"; 
import { Theme } from "../theme.slint";
import { AppLogic } from "../globals.slint";

component ControlButton inherits Rectangle {
    // in property<string> text;
    in property<image> icon;
    
    border-radius: Theme.radius;
    min-width: 64px;
    min-height: 32px;

    border-width: Theme.border-width;
    border-color: Theme.border-color;
}


export component AppControls inherits Rectangle {
    HorizontalLayout {
        spacing: Theme.gap;
        padding: Theme.padding;

        ControlButton {
            areaPlay := TouchArea { clicked => { AppLogic.cb-exit(); } }
            background: areaPlay.has-hover ? Theme.button-hover : Theme.button;

            PlayIcon {
                size: Theme.icon-size;
                colorize: Theme.icon-color;
            }
        }
        ControlButton { 
            areaStop := TouchArea { clicked => { AppLogic.cb-exit(); } }
            background: areaStop.has-hover ? Theme.button-hover : Theme.button;

            OctagonXIcon {
                size: Theme.icon-size;
                colorize: Theme.icon-color;
            }
        }
        ControlButton {             
            areaStep := TouchArea { clicked => { AppLogic.cb-exit(); } }
            background: areaStep.has-hover ? Theme.button-hover : Theme.button;

            StepForwardIcon {
                size: Theme.icon-size;
                colorize: Theme.icon-color;
            }
        }
        ControlButton { 
            areaHelp := TouchArea { clicked => { AppLogic.cb-exit(); } }
            background: areaHelp.has-hover ? Theme.button-hover : Theme.button;

            BadgeQuestionMarkIcon {
                size: Theme.icon-size;
                colorize: Theme.icon-color;
            }
        }
    }
}