
import { StandardButton, Button, VerticalBox } from "std-widgets.slint";
import { PlayIcon, OctagonXIcon, StepForwardIcon, MicrochipIcon, 
         BadgeQuestionMarkIcon, RotateCcwIcon, FolderOpenIcon, BinaryIcon, 
         GamepadDirectionalIcon } from "@lucide"; 
import { Theme } from "../theme.slint";
import { AppLogic } from "../globals.slint";
import { ControlButton } from "../components/controlbutton.slint";


// component ControlButton inherits Rectangle {
//     // in property<string> text;
//     in property<image> icon;
    
//     border-radius: Theme.radius;
//     width: 64px;   
//     height: 32px;

//     border-width: Theme.border-width;
//     border-color: Theme.border-color;
// }


export component AppControls inherits Rectangle {
    VerticalLayout {
        padding: 10px;
        padding-left: 10px;
        spacing: Theme.gap;

        Rectangle { 
            // row:0; col:0; colspan: 6; 

            border-radius: Theme.radius;
            min-width: 64px;
            height: 32px;

            border-width: Theme.border-width;
            border-color: Theme.border-color;
            background: Theme.cell;

            HorizontalLayout {
                GamepadDirectionalIcon {
                    opacity: 1;
                    size: Theme.icon-size;
                    colorize: Theme.icon-color;
                    vertical-alignment: ImageVerticalAlignment.center;
                    height: 32px;
                    width: 32px;
                }
                Text { 
                    color: Theme.text; font-weight: Theme.weight-bold; text: "Emulator Control"; width: 100%; horizontal-alignment: left; vertical-alignment: center; 
                }
            }
        }  


        HorizontalLayout {
            spacing: Theme.gap;

            ControlButton {
                // row: 1; col:0;
                areaPlay := TouchArea { clicked => { AppLogic.cb-run(); } }
                background: areaPlay.has-hover ? Theme.button-hover : Theme.button;

                PlayIcon {
                    size: Theme.icon-size;
                    colorize: Theme.icon-color;
                }
            }
            ControlButton { 
                // row: 1; col:1;
                areaStop := TouchArea { clicked => { AppLogic.cb-stop(); } }
                background: areaStop.has-hover ? Theme.button-hover : Theme.button;

                OctagonXIcon {
                    size: Theme.icon-size;
                    colorize: Theme.icon-color;
                }
            }
            ControlButton {  
                // row: 1; col:2;           
                areaStep := TouchArea { clicked => { AppLogic.cb-step(); } }
                background: areaStep.has-hover ? Theme.button-hover : Theme.button;

                StepForwardIcon {
                    size: Theme.icon-size;
                    colorize: Theme.icon-color;
                }
            }
            ControlButton { 
                // row: 1; col:3;
                areaHelp := TouchArea { clicked => { AppLogic.cb-reset(); } }
                background: areaHelp.has-hover ? Theme.button-hover : Theme.button;

                RotateCcwIcon {
                    size: Theme.icon-size;
                    colorize: Theme.icon-color;
                }
            }
            ControlButton { 
                // row: 1; col:4;
                areaOpen := TouchArea { clicked => { AppLogic.cb-insert-rom(); } }
                background: areaOpen.has-hover ? Theme.button-hover : Theme.button;

                FolderOpenIcon {
                    size: Theme.icon-size;
                    colorize: Theme.icon-color;
                }
            }        
            ControlButton { 
                // row: 1; col:5;
                areaRam := TouchArea { clicked => { AppLogic.cb-show-memory(); } }
                background: areaRam.has-hover ? Theme.button-hover : Theme.button;

                MicrochipIcon {
                    size: Theme.icon-size;
                    colorize: Theme.icon-color;
                }
            }    
        }       
    }

}