import { Theme } from "../theme.slint";
import { AppLogic } from "../globals.slint";
import { BinaryIcon } from "@lucide"; 

export global HardwareState {
    in-out property <string> latch_0;
    in-out property <string> latch_1;
    in-out property <string> latch_2;

    callback sync();
}

component InfoCell inherits Rectangle {
    in property<string> text;
    
    border-radius: Theme.radius;
    min-width: 64px;
    height: 32px;

    border-width: Theme.border-width;
    border-color: Theme.border-color;
    background: Theme.cell;

    HorizontalLayout {
        padding-left: 5px;
        Rectangle { 
            Text { 
                color: Theme.text; text: text; width: 100%; horizontal-alignment: left;  
            }
        }
    }
}



export component Hardware inherits Rectangle {
    GridLayout {
        spacing: Theme.gap;
        padding: Theme.padding;
        padding-top: 10px;

        Rectangle { 
            row:0; col:0; colspan: 3; 

            border-radius: Theme.radius;
            min-width: 64px;
            height: 32px;

            border-width: Theme.border-width;
            border-color: Theme.border-color;
            background: Theme.cell;

            HorizontalLayout {
                BinaryIcon {
                    opacity: 1;
                    size: Theme.icon-size;
                    colorize: Theme.icon-color;
                    vertical-alignment: ImageVerticalAlignment.center;
                    height: 32px;
                    width: 32px;
                }
                Text { 
                    color: Theme.text; font-weight: Theme.weight-bold; text: "Hardware Latch States"; width: 100%; horizontal-alignment: left; vertical-alignment: center; 
                }
            }
        }            
        
        InfoCell { text: HardwareState.latch_0; row:1; col:0; }
        InfoCell { text: HardwareState.latch_1; row:1; col:1; }
        InfoCell { text: HardwareState.latch_2; row:1; col:2; }
    }
   
}