import { ScrollView, Button, LineEdit } from "std-widgets.slint";
import { Theme } from "../theme.slint";
import { AppLogic } from "../globals.slint";
import { ChevronLeftIcon, ChevronRightIcon } from "@lucide"; 


export global MemoryViewData {
    in property<[string]> addresses;       // formatted address per row
    in property<[[string]]> hexBytes;      // hex bytes per row
    in property<[[string]]> asciiChars;    // ascii chars per row
    in property<int> pcRow;
    in property<int> pcCol;
    in property<int> windowStartAddress;
    in property<int> windowSize;
}

component ControlButton inherits Rectangle {
    // in property<string> text;
    in property<image> icon;
    
    border-radius: Theme.radius;
    min-width: 64px;
    min-height: 12px;
    
    border-width: Theme.border-width;
    border-color: Theme.border-color;
}

export component MemoryView inherits Window {
    width: 900px;
    height: 405px;
    background: Theme.app-background;

    VerticalLayout {
        spacing: Theme.gap;
        padding: Theme.padding;

        // Controls
        HorizontalLayout {
            spacing: 12px;


            LineEdit {
                width: 120px;
                placeholder-text: "Goto (hex)";
 
                accepted(text) => {
                    AppLogic.goto_location(text);
                }
            }

            ControlButton {
                areaPrev := TouchArea { clicked => { AppLogic.previous_page(); } }
                background: areaPrev.has-hover ? Theme.button-hover : Theme.button;
                
                ChevronLeftIcon {
                    size: Theme.icon-size;
                    colorize: Theme.icon-color;
                }
            }
            ControlButton {
                areaNext := TouchArea { clicked => { AppLogic.next_page(); } }
                background: areaNext.has-hover ? Theme.button-hover : Theme.button;

                ChevronRightIcon {
                    size: Theme.icon-size;
                    colorize: Theme.icon-color;
                }
            }
            
            Rectangle { width: 1px; } // Spacer

            Text {
                color: #888;
                font-family: "monospace";
                vertical-alignment: center;
                text: "Window: 0x" + MemoryViewData.windowStartAddress + " (" + MemoryViewData.windowSize + " bytes)";
            }

        }

        // Memory grid 
        Rectangle {
            background: Theme.app-background;
            border-radius: Theme.radius;
            clip: true;

            ScrollView {
                width: parent.width;
                height: parent.height;

                VerticalLayout {
                    spacing: 0px;
                    
                    for row in MemoryViewData.addresses.length: Rectangle {
                        height: 22px;
                        background: Theme.cell;

                        HorizontalLayout {
                            spacing: 8px;
                            padding-left: 2px;
                            padding-top: 2px;

                            // Address column data
                            Text { 
                                width: 80px;
                                color: Theme.text;
                                font-family: "monospace";
                                text: MemoryViewData.addresses[row];
                            }

                            // Hex Bytes
                            for col in 16: Rectangle {
                                width: 28px;
                                height: 20px;
                                border-radius: Theme.radius-thin;

                                background: (row == MemoryViewData.pcRow && col == MemoryViewData.pcCol) ? Theme.pc-cell : Theme.cell;

                                Text {
                                    horizontal-alignment: center;
                                    vertical-alignment: center;
                                    font-family: "monospace";
                                    font-size: 11px;
                                    color: (row == MemoryViewData.pcRow && col == MemoryViewData.pcCol) ? Theme.pc-cell-text : Theme.text;
                                    text: MemoryViewData.hexBytes[row][col];
                                }
                            }

                            // ASCII View
                            HorizontalLayout {
                                spacing: 0;
                                for col in 16: Text {
                                    width: 12px;
                                    font-family: "monospace";
                                    color: Theme.text;
                                    text: MemoryViewData.asciiChars[row][col];
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
