import { Theme } from "../theme.slint";
import { AppLogic } from "../globals.slint";


export global EmulatorRegisters {
    in-out property <int> pc;
    in-out property <int> sp;
    in-out property <int> a;
    in-out property <int> b;
    in-out property <int> c;
    in-out property <int> e;
    in-out property <int> h;
    in-out property <int> l;

    callback sync();
}

component InfoCell inherits Rectangle {
    in property<string> text;
    
    border-radius: Theme.radius;
    min-width: 64px;
    min-height: 32px;

    border-width: Theme.border-width;
    border-color: Theme.border-color;
    background: Theme.cell;

    Text { color: Theme.text; text: text; width: 90%; horizontal-alignment: left;  }
}


export component Registers inherits Rectangle {
    GridLayout {
        spacing: Theme.gap;
        padding: Theme.padding;
        
        InfoCell { text: "A: "+EmulatorRegisters.a; row:0; col:0; }
        InfoCell { text: "B: "+EmulatorRegisters.b; row:0; col:1; }
        InfoCell { text: "C: "+EmulatorRegisters.c; row:0; col:2; }
        InfoCell { text: "E: "+EmulatorRegisters.e; row:0; col:3; }
        InfoCell { text: "H: "+EmulatorRegisters.h; row:1; col:0; }
        InfoCell { text: "L: "+EmulatorRegisters.l; row:1; col:1; }
        InfoCell { text: "SP: "+EmulatorRegisters.sp; row:2; col:0; colspan: 2; }
        InfoCell { text: "PC: "+EmulatorRegisters.pc; row:2; col:2; colspan: 2; }

    }
}