import { Theme } from "../theme.slint";
import { AppLogic } from "../globals.slint";
import { BlocksIcon } from "../vendor/lucide.slint";

export global EmulatorRegisters {
    in-out property <int> pc;
    in property<string> pc-hex;
    in-out property <int> sp;
    in property<string> sp-hex;
    in-out property <int> a;
    in-out property <int> b;
    in-out property <int> c;
    in-out property <int> e;
    in-out property <int> h;
    in-out property <int> l;

    callback sync();
}

component InfoCell inherits Rectangle {
    in property<string> text;
    
    border-radius: Theme.radius;

    height: 32px;

    border-width: Theme.border-width;
    border-color: Theme.border-color;
    background: Theme.cell;

    HorizontalLayout {
        padding-left: 5px;
        Rectangle { 
            Text { 
                color: Theme.text; text: text; width: 100%; horizontal-alignment: left;  
            }
        }
    }
}


export component Registers inherits Rectangle {
    GridLayout {
        padding: 10px;
        padding-left: 10px;
        spacing: Theme.gap;
        

        Rectangle { 
            row:0; col:0; colspan: 6; 

            border-radius: Theme.radius;
            min-width: 64px;
            height: 32px;

            border-width: Theme.border-width;
            border-color: Theme.border-color;
            background: Theme.cell;

            HorizontalLayout {
                BlocksIcon {
                    opacity: 1;
                    size: Theme.icon-size;
                    colorize: Theme.icon-color;
                    vertical-alignment: ImageVerticalAlignment.center;
                    height: 32px;
                    width: 32px;
                }
                Text { 
                    color: Theme.text; font-weight: Theme.weight-bold; text: "Registers"; width: 100%; horizontal-alignment: left; vertical-alignment: center; 
                }
            }
        } 


        InfoCell { text: "A: "+EmulatorRegisters.a; row:1; col:0; }
        InfoCell { text: "B: "+EmulatorRegisters.b; row:1; col:1; }
        InfoCell { text: "C: "+EmulatorRegisters.c; row:1; col:2; }
        InfoCell { text: "E: "+EmulatorRegisters.e; row:1; col:3; }
        InfoCell { text: "H: "+EmulatorRegisters.h; row:1; col:4; }
        InfoCell { text: "L: "+EmulatorRegisters.l; row:1; col:5; }
        InfoCell { text: "SP: 0x"+EmulatorRegisters.sp-hex; row:2; col:0; colspan: 2; }
        InfoCell { text: "PC: 0x"+EmulatorRegisters.pc-hex; row:2; col:2; colspan: 2; }
    }
}